# Generated by Django 5.2.13 on 2026-04-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_promo_kiaba2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.DeleteModel(
            name='PromoCodeUsage',
        ),
    ]
