"""
Django settings for kiaba project.

Generated by 'django-admin startproject' using Django 5.1.2.

This settings module is configured for:
- PostgreSQL (from environment variables)
- Redis cache
- Celery (broker + backend via Redis)
- django-allauth (limited signup will be enforced via a custom adapter later)
- Static/Media (FileSystem by default; S3 via env)
- i18n (fr default, en optional)
- Security headers (baseline)
"""

from pathlib import Path
import os
import sys

try:
    import environ  # type: ignore
except Exception:
    environ = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


if environ is not None:
    env = environ.Env(
        DEBUG=(bool, False),
        SECRET_KEY=(str, "change-me"),
        ALLOWED_HOSTS=(str, "localhost,127.0.0.1"),
        LANGUAGE_CODE=(str, "fr"),
        TIME_ZONE=(str, "Africa/Abidjan"),
        # Database
        DB_ENGINE=(str, "postgres"),  # 'postgres' or 'sqlite'
        POSTGRES_DB=(str, "kiaba"),
        POSTGRES_USER=(str, "kiaba"),
        POSTGRES_PASSWORD=(str, "kiaba"),
        POSTGRES_HOST=(str, "localhost"),
        POSTGRES_PORT=(int, 5432),
        # Redis
        REDIS_URL=(str, "redis://localhost:6379/1"),
        # Static/Media
        DEFAULT_FILE_STORAGE=(str, "django.core.files.storage.FileSystemStorage"),
        STATIC_URL=(str, "/static/"),
        STATIC_ROOT=(str, "staticfiles"),
        MEDIA_URL=(str, "/media/"),
        MEDIA_ROOT=(str, "media"),
        # Email (console backend pour développement)
        EMAIL_BACKEND=(str, "django.core.mail.backends.console.EmailBackend"),
        DEFAULT_FROM_EMAIL=(str, "HABIKO <no-reply@example.com>"),
        SERVER_EMAIL=(str, "HABIKO Errors <errors@example.com>"),
        # CinetPay
        CINETPAY_SITE_ID=(str, ""),
        CINETPAY_API_KEY=(str, ""),
        CINETPAY_SITE_KEY=(str, ""),
        CINETPAY_NOTIFY_URL=(str, "https://ci-habiko.com/accounts/payment/cinetpay/notify/"),
        CINETPAY_RETURN_URL=(str, "https://ci-habiko.com/accounts/payment/cinetpay/return/"),
    )
    environ.Env.read_env(os.path.join(Path(__file__).resolve().parent.parent, ".env"))
else:

    class _DummyEnv:
        def __init__(self, **schema):
            self.schema = schema

        def __call__(self, key, default=None):
            if default is None and key in self.schema:
                default = self.schema[key][1]
            value = os.environ.get(key, default)
            return value

        def int(self, key, default=0):
            try:
                return int(os.environ.get(key, default))
            except Exception:
                return default

    env = _DummyEnv(
        DEBUG=(bool, False),
        SECRET_KEY=(str, "change-me"),
        ALLOWED_HOSTS=(str, "localhost,127.0.0.1"),
        LANGUAGE_CODE=(str, "fr"),
        TIME_ZONE=(str, "Africa/Abidjan"),
        DB_ENGINE=(str, "postgres"),
        POSTGRES_DB=(str, "kiaba"),
        POSTGRES_USER=(str, "kiaba"),
        POSTGRES_PASSWORD=(str, "kiaba"),
        POSTGRES_HOST=(str, "localhost"),
        POSTGRES_PORT=(int, 5432),
        REDIS_URL=(str, "redis://localhost:6379/1"),
        DEFAULT_FILE_STORAGE=(str, "django.core.files.storage.FileSystemStorage"),
        STATIC_URL=(str, "/static/"),
        STATIC_ROOT=(str, "staticfiles"),
        MEDIA_URL=(str, "/media/"),
        MEDIA_ROOT=(str, "media"),
        EMAIL_BACKEND=(str, "django.core.mail.backends.console.EmailBackend"),
        DEFAULT_FROM_EMAIL=(str, "HABIKO <no-reply@example.com>"),
        SERVER_EMAIL=(str, "HABIKO Errors <errors@example.com>"),
        # CinetPay
        CINETPAY_SITE_ID=(str, ""),
        CINETPAY_API_KEY=(str, ""),
        CINETPAY_SITE_KEY=(str, ""),
        CINETPAY_NOTIFY_URL=(str, "https://ci-habiko.com/accounts/payment/cinetpay/notify/"),
        CINETPAY_RETURN_URL=(str, "https://ci-habiko.com/accounts/payment/cinetpay/return/"),
    )

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Convertir DEBUG correctement (les variables d'environnement sont des strings)
debug_val = env("DEBUG")
if isinstance(debug_val, str):
    DEBUG = debug_val.lower() in ("true", "1", "yes", "on")
else:
    DEBUG = bool(debug_val)

ALLOWED_HOSTS = [h.strip() for h in env("ALLOWED_HOSTS").split(",") if h.strip()]

# Add www version and Render external host automatically (uniquement en production)
if not DEBUG:
    ALLOWED_HOSTS.append("www.ci-habiko.com")  # Pour accepter www avant redirection

# Add Render external host automatically if present
RENDER_EXTERNAL_URL = os.environ.get("RENDER_EXTERNAL_URL")
if RENDER_EXTERNAL_URL:
    try:
        from urllib.parse import urlparse

        _r = urlparse(RENDER_EXTERNAL_URL)
        if _r.hostname and _r.hostname not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_r.hostname)
    except Exception:
        pass

# Application definition

INSTALLED_APPS = [
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    # "django.contrib.postgres",  # Désactivé pour SQLite local
    # Third-party
    "rest_framework",
    "django_htmx",
    "corsheaders",
    "imagekit",
    "storages",
    "allauth",
    "allauth.account",
    # Local apps
    "accounts.apps.AccountsConfig",
    "ads",
    "core",
    "moderation",
    "seo",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # En dev on désactive les redirections HTTP->HTTPS pour pouvoir utiliser http://127.0.0.1
    "core.middleware.RedirectMiddleware",  # Redirections HTTP->HTTPS et www->non-www (désactivé si DEBUG=True, voir plus bas)
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# En développement, on ne veut AUCUNE redirection automatique HTTP -> HTTPS
if DEBUG and "core.middleware.RedirectMiddleware" in MIDDLEWARE:
    MIDDLEWARE.remove("core.middleware.RedirectMiddleware")

ROOT_URLCONF = "kiaba.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.site_metrics",
            ],
        },
    },
]

WSGI_APPLICATION = "kiaba.wsgi.application"


# Database (PostgreSQL)
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if "test" in sys.argv or env("DB_ENGINE") == "sqlite":
    # Utiliser SQLite pour tests/dev rapide
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    # Configuration PostgreSQL avec SSL pour Render
    # Vérifier d'abord si DATABASE_URL est fourni par Render (méthode recommandée)
    database_url = os.environ.get("DATABASE_URL")

    if database_url:
        # Render fournit DATABASE_URL automatiquement quand on lie une base de données
        # Utiliser django-environ pour parser DATABASE_URL
        DATABASES = {"default": env.db("DATABASE_URL")}

        # S'assurer que sslmode=prefer est dans OPTIONS pour Render
        if "OPTIONS" not in DATABASES["default"]:
            DATABASES["default"]["OPTIONS"] = {}
        # Utiliser 'prefer' qui essaie SSL mais ne l'exige pas strictement
        # Cela évite les problèmes de validation de certificat
        DATABASES["default"]["OPTIONS"]["sslmode"] = "prefer"
        DATABASES["default"]["CONN_MAX_AGE"] = 0
        DATABASES["default"]["ATOMIC_REQUESTS"] = True
    else:
        # Fallback : utiliser les variables individuelles
        postgres_host = env("POSTGRES_HOST", default="")
        is_render_db = "render.com" in postgres_host.lower() or os.environ.get(
            "RENDER_EXTERNAL_URL"
        )

        # Options de connexion de base
        db_options = {
            "connect_timeout": 10,
        }

        if is_render_db:
            # Sur Render, PostgreSQL exige SSL/TLS pour toutes les connexions
            # Utiliser 'prefer' qui essaie SSL mais ne l'exige pas strictement
            # Cela évite les problèmes de validation de certificat
            db_options["sslmode"] = "prefer"
            # Définir aussi les variables d'environnement pour psycopg2
            os.environ["PGSSLMODE"] = "prefer"
            # Ajouter connect_timeout pour éviter les timeouts
            db_options["connect_timeout"] = 10

        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": env("POSTGRES_DB"),
                "USER": env("POSTGRES_USER"),
                "PASSWORD": env("POSTGRES_PASSWORD"),
                "HOST": postgres_host,
                "PORT": env("POSTGRES_PORT"),
                "OPTIONS": db_options,
                "CONN_MAX_AGE": 0,  # Désactiver le pooling pour éviter les problèmes de connexion
                "ATOMIC_REQUESTS": True,
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "fr"
LANGUAGES = [
    ("fr", "Français"),
    ("en", "English"),
]

TIME_ZONE = env("TIME_ZONE")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = env("STATIC_URL")
_static_root = env("STATIC_ROOT")
if not os.path.isabs(_static_root):
    STATIC_ROOT = BASE_DIR / _static_root
else:
    STATIC_ROOT = _static_root
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# WhiteNoise configuration for media files
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True
# Cache static files for 1 year (31536000 seconds)
WHITENOISE_MAX_AGE = 31536000

# Media
MEDIA_URL = env("MEDIA_URL")
_media_root = env("MEDIA_ROOT")
if not os.path.isabs(_media_root):
    MEDIA_ROOT = BASE_DIR / _media_root
else:
    MEDIA_ROOT = _media_root

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Sites framework
SITE_ID = 1
# En développement, utiliser localhost:8080, sinon utiliser le domaine de production
if DEBUG:
    SITE_URL = env("SITE_URL", default="http://localhost:8080")
else:
    SITE_URL = env("SITE_URL", default="https://ci-habiko.com")

# Caches (Forcer le cache local pour éviter les erreurs Redis)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

# DRF (prepare throttling for rate limiting contact clicks)
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/minute",
        "user": "300/minute",
    },
}

# CSRF / Security
_base_csrf = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:8001",
    "http://127.0.0.1:8001",
]
_dynamic_csrf = []
try:
    from urllib.parse import urlparse as _urlparse

    if SITE_URL:
        _s = _urlparse(SITE_URL)
        if _s.scheme and _s.netloc:
            _dynamic_csrf.append(f"{_s.scheme}://{_s.netloc}")
    if RENDER_EXTERNAL_URL:
        _r = _urlparse(RENDER_EXTERNAL_URL)
        if _r.scheme and _r.netloc:
            _dynamic_csrf.append(f"{_r.scheme}://{_r.netloc}")
except Exception:
    pass
CSRF_TRUSTED_ORIGINS = _base_csrf + _dynamic_csrf
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "DENY"
# En développement, désactiver les cookies sécurisés (nécessaire pour HTTP local)
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
# Renforcer la protection des cookies en toutes circonstances
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
# Politique de referrer plus stricte
SECURE_REFERRER_POLICY = "same-origin"
# Désactiver complètement HSTS en développement pour éviter les redirections HTTPS forcées
SECURE_HSTS_SECONDS = 0  # Toujours 0 pour permettre HTTP en local
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
# Configuration HTTPS pour les proxies (Render, etc.)
# Render passe le header X-Forwarded-Proto pour indiquer HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# Forcer Django à considérer les requêtes comme sécurisées si le proxy indique HTTPS
USE_TLS = not DEBUG

# CORS (if needed for future API)
CORS_ALLOW_ALL_ORIGINS = DEBUG

"""
Email configuration
- En dev : backend console par défaut
- En prod : SMTP professionnel configuré via variables d'environnement
"""

EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend",
)

# Identité d'envoi
DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default="HABIKO <no-replay@ci-habiko.com>",
)
SERVER_EMAIL = env(
    "SERVER_EMAIL",
    default="HABIKO Errors <no-replay@ci-habiko.com>",
)

# Paramètres SMTP (utilisés si EMAIL_BACKEND est un backend SMTP)
EMAIL_HOST = env("EMAIL_HOST", default="mail.ci-habiko.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=465)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="no-replay@ci-habiko.com")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")

# SSL/TLS : pour ton hébergeur, tu peux utiliser soit 465+SSL, soit 587+TLS
EMAIL_USE_SSL = env("EMAIL_USE_SSL", default="True").lower() in ("true", "1", "yes")
EMAIL_USE_TLS = env("EMAIL_USE_TLS", default="False").lower() in ("true", "1", "yes")

EMAIL_TIMEOUT = env.int(
    "EMAIL_TIMEOUT", default=5
)  # Timeout réduit pour éviter de bloquer l'inscription
EMAIL_USE_LOCALTIME = True
EMAIL_SUBJECT_PREFIX = "[HABIKO] "
EMAIL_USE_8BIT = False
EMAIL_CHARSET = "utf-8"

# Resend HTTP API key for transactional emails (recommandé, plus simple et fiable)
RESEND_API_KEY = env("RESEND_API_KEY", default="")

# Brevo (Sendinblue) HTTP API key for transactional emails (fallback)
BREVO_API_KEY = env("BREVO_API_KEY", default="")

# En développement local, forcer l'utilisation du SMTP au lieu du backend console
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Storage
DEFAULT_FILE_STORAGE = env("DEFAULT_FILE_STORAGE")

# Google Analytics
GA_MEASUREMENT_ID = env("GA_MEASUREMENT_ID", default=None)

# Google AdSense
ADSENSE_PUBLISHER_ID = env("ADSENSE_PUBLISHER_ID", default=None)  # Format: ca-pub-XXXXXXXXXX
ADSENSE_ENABLED = env("ADSENSE_ENABLED", default="False").lower() in ("true", "1", "yes")

# Celery (broker/backend via Redis ou base de données)
REDIS_URL = env("REDIS_URL", default=None)
if REDIS_URL and REDIS_URL.strip():
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL
    CELERY_TASK_ALWAYS_EAGER = False  # Utiliser Celery avec Redis
else:
    # Fallback vers base de données pour le développement
    CELERY_BROKER_URL = "memory://"
    CELERY_RESULT_BACKEND = "cache+memory://"
    # En production sans Redis, exécuter les tâches Celery en mode synchrone
    CELERY_TASK_ALWAYS_EAGER = True  # Mode synchrone si pas de Redis

CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_BEAT_SCHEDULE = {
    "expire-ads-daily": {
        "task": "ads.tasks.expire_ads",
        "schedule": 60 * 60 * 24,  # quotidien
    }
}

# Sitemaps
SITEMAP_PROTOCOL = "https"

# Authentication backends (allauth + Django)
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

# allauth basic settings (we'll restrict provider signups later via adapter/forms)
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Obligatoire pour valider les comptes
LOGIN_REDIRECT_URL = "/dashboard"
LOGIN_URL = "/auth/login/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
ACCOUNT_EMAIL_CONFIRMATION_AUTO_LOGIN = True
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "/auth/login/"
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "/dashboard/"

# Rate limiting allauth pour limiter les tentatives de bruteforce & abus
# (utilise le cache Django ; ici LocMem en production sans Redis)
ACCOUNT_RATE_LIMITS = {
    "login_failed": "5/5m",  # max 5 échecs de login / 5 minutes par IP+user
    "signup": "3/h",  # max 3 inscriptions / heure
    "reset_password": "3/h",  # max 3 demandes de reset / heure
}

# Désactiver la page de confirmation de déconnexion
ACCOUNT_LOGOUT_ON_GET = True

# Utiliser l'adaptateur personnalisé
ACCOUNT_ADAPTER = "accounts.adapters.NoRateLimitAccountAdapter"

# Utiliser les formulaires personnalisés
ACCOUNT_FORMS = {
    "login": "accounts.forms.CustomLoginForm",
    "signup": "accounts.forms.CustomSignupForm",
}

# Custom user model
AUTH_USER_MODEL = "accounts.CustomUser"

# CinetPay configuration
CINETPAY_SITE_ID = env("CINETPAY_SITE_ID", default="")
CINETPAY_API_KEY = env("CINETPAY_API_KEY", default="")
CINETPAY_SITE_KEY = env("CINETPAY_SITE_KEY", default="")
CINETPAY_MODE = env("CINETPAY_MODE", default="PRODUCTION")  # PRODUCTION ou TEST
CINETPAY_NOTIFY_URL = env(
    "CINETPAY_NOTIFY_URL", default="https://ci-habiko.com/accounts/payment/cinetpay/notify/"
)
CINETPAY_RETURN_URL = env(
    "CINETPAY_RETURN_URL", default="https://ci-habiko.com/accounts/payment/cinetpay/return/"
)
