"""
Django settings for kiaba project.

Generated by 'django-admin startproject' using Django 5.1.2.

This settings module is configured for:
- PostgreSQL (from environment variables)
- Redis cache
- Celery (broker + backend via Redis)
- django-allauth (limited signup will be enforced via a custom adapter later)
- Static/Media (FileSystem by default; S3 via env)
- i18n (fr default, en optional)
- Security headers (baseline)
"""

from pathlib import Path
import os
import sys
import logging

logger = logging.getLogger(__name__)

try:
    import environ  # type: ignore
except Exception:
    environ = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


if environ is not None:
    env = environ.Env(
        DEBUG=(bool, False),
        SECRET_KEY=(str, "change-me"),
        ALLOWED_HOSTS=(str, "localhost,127.0.0.1"),
        LANGUAGE_CODE=(str, "fr"),
        TIME_ZONE=(str, "Africa/Abidjan"),
        # Database
        DB_ENGINE=(str, "postgres"),  # 'postgres' or 'sqlite'
        POSTGRES_DB=(str, "kiaba"),
        POSTGRES_USER=(str, "kiaba"),
        POSTGRES_PASSWORD=(str, "kiaba"),
        POSTGRES_HOST=(str, "localhost"),
        POSTGRES_PORT=(int, 5432),
        # Redis
        REDIS_URL=(str, "redis://localhost:6379/1"),
        # Static/Media
        DEFAULT_FILE_STORAGE=(str, "django.core.files.storage.FileSystemStorage"),
        STATIC_URL=(str, "/static/"),
        STATIC_ROOT=(str, "staticfiles"),
        MEDIA_URL=(str, "/media/"),
        MEDIA_ROOT=(str, "media"),
        # Email (console backend pour développement)
        EMAIL_BACKEND=(str, "django.core.mail.backends.console.EmailBackend"),
        DEFAULT_FROM_EMAIL=(str, "KIABA Rencontres <no-reply@example.com>"),
        SERVER_EMAIL=(str, "KIABA Rencontres Errors <errors@example.com>"),
        # CinetPay
        CINETPAY_SITE_ID=(str, ""),
        CINETPAY_API_KEY=(str, ""),
        CINETPAY_SITE_KEY=(str, ""),
        CINETPAY_NOTIFY_URL=(str, "https://ci-kiaba.com/accounts/payment/cinetpay/notify/"),
        CINETPAY_RETURN_URL=(str, "https://ci-kiaba.com/accounts/payment/cinetpay/return/"),
    )
    environ.Env.read_env(os.path.join(Path(__file__).resolve().parent.parent, ".env"))
else:

    class _DummyEnv:
        def __init__(self, **schema):
            self.schema = schema

        def __call__(self, key, default=None):
            if default is None and key in self.schema:
                default = self.schema[key][1]
            value = os.environ.get(key, default)
            return value

        def int(self, key, default=0):
            try:
                return int(os.environ.get(key, default))
            except Exception:
                return default

        def db(self, key, default=None):
            """Parse DATABASE_URL when django-environ is not available."""
            from urllib.parse import urlparse, unquote_plus

            url = os.environ.get(key, default)
            if not url:
                raise ValueError(f"{key} is not set")
            parsed = urlparse(url)
            path = parsed.path.lstrip("/") or "postgres"
            return {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": path,
                "USER": unquote_plus(parsed.username) if parsed.username else "",
                "PASSWORD": unquote_plus(parsed.password) if parsed.password else "",
                "HOST": parsed.hostname or "",
                "PORT": str(parsed.port) if parsed.port else "5432",
            }

    env = _DummyEnv(
        DEBUG=(bool, False),
        SECRET_KEY=(str, "change-me"),
        ALLOWED_HOSTS=(str, "localhost,127.0.0.1"),
        LANGUAGE_CODE=(str, "fr"),
        TIME_ZONE=(str, "Africa/Abidjan"),
        DB_ENGINE=(str, "postgres"),
        POSTGRES_DB=(str, "kiaba"),
        POSTGRES_USER=(str, "kiaba"),
        POSTGRES_PASSWORD=(str, "kiaba"),
        POSTGRES_HOST=(str, "localhost"),
        POSTGRES_PORT=(int, 5432),
        REDIS_URL=(str, "redis://localhost:6379/1"),
        DEFAULT_FILE_STORAGE=(str, "django.core.files.storage.FileSystemStorage"),
        STATIC_URL=(str, "/static/"),
        STATIC_ROOT=(str, "staticfiles"),
        MEDIA_URL=(str, "/media/"),
        MEDIA_ROOT=(str, "media"),
        EMAIL_BACKEND=(str, "django.core.mail.backends.console.EmailBackend"),
        DEFAULT_FROM_EMAIL=(str, "KIABA Rencontres <no-reply@example.com>"),
        SERVER_EMAIL=(str, "KIABA Rencontres Errors <errors@example.com>"),
        # CinetPay
        CINETPAY_SITE_ID=(str, ""),
        CINETPAY_API_KEY=(str, ""),
        CINETPAY_SITE_KEY=(str, ""),
        CINETPAY_NOTIFY_URL=(str, "https://ci-kiaba.com/accounts/payment/cinetpay/notify/"),
        CINETPAY_RETURN_URL=(str, "https://ci-kiaba.com/accounts/payment/cinetpay/return/"),
    )

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Convertir DEBUG correctement (les variables d'environnement sont des strings)
debug_val = env("DEBUG")
if isinstance(debug_val, str):
    DEBUG = debug_val.lower() in ("true", "1", "yes", "on")
else:
    DEBUG = bool(debug_val)

# Empêcher le démarrage en production avec des valeurs par défaut dangereuses
if not DEBUG:
    if SECRET_KEY == "change-me":
        raise RuntimeError(
            "SECRET_KEY non configurée. Définissez la variable d'environnement SECRET_KEY."
        )

ALLOWED_HOSTS = [h.strip() for h in env("ALLOWED_HOSTS").split(",") if h.strip()]

# Add www version and Render external host automatically (uniquement en production)
if not DEBUG:
    ALLOWED_HOSTS.append("www.ci-kiaba.com")  # Pour accepter www avant redirection

# Add Render external host automatically if present
RENDER_EXTERNAL_URL = os.environ.get("RENDER_EXTERNAL_URL")
if RENDER_EXTERNAL_URL:
    try:
        from urllib.parse import urlparse

        _r = urlparse(RENDER_EXTERNAL_URL)
        if _r.hostname and _r.hostname not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_r.hostname)
    except Exception:
        pass

# Age gate 18+ : modale affichée à chaque nouvelle session (après fermeture du navigateur)
# Ne s'affiche pas pour les utilisateurs connectés.
ENABLE_AGE_GATE = True

# Add Vercel host automatically if present
VERCEL_URL = os.environ.get("VERCEL_URL")
if VERCEL_URL and VERCEL_URL not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(VERCEL_URL)
    ALLOWED_HOSTS.append(f".{VERCEL_URL}")  # Pour les sous-domaines *.vercel.app

# Application definition

INSTALLED_APPS = [
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    # "django.contrib.postgres",  # Désactivé pour SQLite local
    # Third-party
    "rest_framework",
    "django_htmx",
    "corsheaders",
    "imagekit",
    "storages",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    # Local apps
    "accounts.apps.AccountsConfig",
    "ads",
    "core",
    "moderation",
    "seo",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # Compression gzip pour améliorer les performances
    "core.middleware.GZipCompressionMiddleware",
    # Cache agressif pour static / media (images d'annonces)
    "core.middleware.StaticMediaCacheMiddleware",
    # En dev on désactive les redirections HTTP->HTTPS pour pouvoir utiliser http://127.0.0.1
    "core.middleware.RedirectMiddleware",  # Redirections HTTP->HTTPS et www->non-www (désactivé si DEBUG=True, voir plus bas)
    "core.middleware.CloudflareMiddleware",  # Récupère l'IP réelle depuis Cloudflare (CF-Connecting-IP)
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "core.middleware.CsrfExemptPasswordResetFromKeyMiddleware",  # POST reset mot de passe (lien email) sans CSRF pour mobile
    "django.middleware.csrf.CsrfViewMiddleware",
    "core.middleware.EnsureCsrfCookieForAuthMiddleware",  # Cookie CSRF sur GET /auth/*
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "core.middleware.ConsumeMessagesAfterResponseMiddleware",  # Message affiché une seule fois
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# En développement, on ne veut AUCUNE redirection automatique HTTP -> HTTPS
if DEBUG and "core.middleware.RedirectMiddleware" in MIDDLEWARE:
    MIDDLEWARE.remove("core.middleware.RedirectMiddleware")

ROOT_URLCONF = "kiaba.urls"

# Configuration des templates avec cache en production
_template_options = {
    "context_processors": [
        "django.template.context_processors.debug",
        "django.template.context_processors.request",
        "django.contrib.auth.context_processors.auth",
        "django.contrib.messages.context_processors.messages",
        "core.context_processors.site_metrics",
    ],
}

# En production, activer le cache de template pour améliorer les performances
if not DEBUG:
    _template_options["loaders"] = [
        (
            "django.template.loaders.cached.Loader",
            [
                "django.template.loaders.filesystem.Loader",
                "django.template.loaders.app_directories.Loader",
            ],
        )
    ]
    # APP_DIRS doit être False quand loaders est défini
    _template_app_dirs = False
else:
    # En DEBUG, utiliser APP_DIRS (plus simple pour le développement)
    _template_app_dirs = True

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": _template_app_dirs,
        "OPTIONS": _template_options,
    },
]

WSGI_APPLICATION = "kiaba.wsgi.application"


# Database (PostgreSQL)
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if "test" in sys.argv or env("DB_ENGINE") == "sqlite":
    # Utiliser SQLite pour tests/dev rapide
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    # Configuration PostgreSQL avec SSL pour Render
    # Vérifier d'abord si DATABASE_URL est fourni par Render (méthode recommandée)
    database_url = os.environ.get("DATABASE_URL")

    if database_url:
        # Vercel serverless : Supabase direct (db.xxx.supabase.co) est IPv6-only, échoue avec "Cannot assign requested address"
        # Convertir automatiquement vers le pooler (IPv4 compatible) quand on est sur Vercel
        _vercel = os.environ.get("VERCEL") == "1"
        if _vercel and "db." in database_url and ".supabase.co" in database_url and "pooler.supabase.com" not in database_url:
            import re
            # Extraire project ref : db.PROJECT_REF.supabase.co
            _m = re.search(r"db\.([a-z0-9]+)\.supabase\.co", database_url)
            if _m:
                _ref = _m.group(1)
                _region = os.environ.get("SUPABASE_POOLER_REGION", "eu-central-1")
                _pooler_host = f"aws-0-{_region}.pooler.supabase.com"
                # Remplacer db.XXX.supabase.co par pooler host, et forcer port 6543
                database_url = re.sub(r"db\.[a-z0-9]+\.supabase\.co(:\d+)?", f"{_pooler_host}:6543", database_url)
                # User pooler : postgres.PROJECT_REF au lieu de postgres
                if f"postgres.{_ref}" not in database_url and "postgres:" in database_url:
                    database_url = database_url.replace("postgres:", f"postgres.{_ref}:", 1)
                os.environ["DATABASE_URL"] = database_url
                logger.info("🔄 DATABASE_URL converti vers Supabase pooler (IPv4) pour Vercel")

        # Render fournit DATABASE_URL automatiquement quand on lie une base de données
        # Utiliser django-environ pour parser DATABASE_URL
        DATABASES = {"default": env.db("DATABASE_URL")}

        # S'assurer que sslmode=prefer est dans OPTIONS pour Render
        if "OPTIONS" not in DATABASES["default"]:
            DATABASES["default"]["OPTIONS"] = {}
        # Utiliser 'prefer' qui essaie SSL mais ne l'exige pas strictement
        # Cela évite les problèmes de validation de certificat
        DATABASES["default"]["OPTIONS"]["sslmode"] = "prefer"
        # Réutiliser les connexions DB en production (sauf Vercel serverless)
        DATABASES["default"]["CONN_MAX_AGE"] = 0 if os.environ.get("VERCEL") == "1" else 60
        DATABASES["default"]["ATOMIC_REQUESTS"] = True
    else:
        # Fallback : utiliser les variables individuelles
        postgres_host = env("POSTGRES_HOST", default="")
        is_render_db = "render.com" in postgres_host.lower() or os.environ.get("RENDER_EXTERNAL_URL")
        is_supabase_db = "supabase.co" in postgres_host.lower()

        # Options de connexion de base
        db_options = {
            "connect_timeout": 10,
        }

        if is_render_db or is_supabase_db:
            # Sur Render, PostgreSQL exige SSL/TLS pour toutes les connexions
            # Utiliser 'prefer' qui essaie SSL mais ne l'exige pas strictement
            # Cela évite les problèmes de validation de certificat
            db_options["sslmode"] = "prefer"
            # Définir aussi les variables d'environnement pour psycopg2
            os.environ["PGSSLMODE"] = "prefer"
            # Ajouter connect_timeout pour éviter les timeouts
            db_options["connect_timeout"] = 10

        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": env("POSTGRES_DB"),
                "USER": env("POSTGRES_USER"),
                "PASSWORD": env("POSTGRES_PASSWORD"),
                "HOST": postgres_host,
                "PORT": env("POSTGRES_PORT"),
                "OPTIONS": db_options,
                "CONN_MAX_AGE": 0 if os.environ.get("VERCEL") == "1" else 60,
                "ATOMIC_REQUESTS": True,
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "fr"
LANGUAGES = [
    ("fr", "Français"),
    ("en", "English"),
]

TIME_ZONE = env("TIME_ZONE")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = env("STATIC_URL")
_static_root = env("STATIC_ROOT")
if not os.path.isabs(_static_root):
    STATIC_ROOT = BASE_DIR / _static_root
else:
    STATIC_ROOT = _static_root
STATICFILES_DIRS = [BASE_DIR / "static"]
# STATICFILES_STORAGE défini plus bas (aligné sur STORAGES / Vercel)

# WhiteNoise configuration for media files
WHITENOISE_USE_FINDERS = True
# En production, désactiver AUTOREFRESH pour forcer la re-collection des fichiers statiques
WHITENOISE_AUTOREFRESH = DEBUG  # True en dev, False en prod
# Cache static files for 1 year (31536000 seconds)
# Note: Avec CompressedManifestStaticFilesStorage, les fichiers avec hash changent automatiquement
# mais le cache navigateur peut garder l'ancienne version. Pour forcer le refresh, on peut :
# 1. Vider le cache navigateur (Ctrl+Shift+R ou Cmd+Shift+R)
# 2. Utiliser un paramètre de version dans l'URL (ex: ?v=2.0)
WHITENOISE_MAX_AGE = 31536000

# Media
MEDIA_URL = env("MEDIA_URL")
_media_root = env("MEDIA_ROOT")

# Détection de la plateforme de déploiement
RENDER_EXTERNAL_URL = os.environ.get("RENDER_EXTERNAL_URL")
VERCEL = os.environ.get("VERCEL") == "1"
is_render = bool(RENDER_EXTERNAL_URL) or os.path.exists("/app/media")

# Configuration Media selon la plateforme
# Sur Vercel le disque est en lecture seule : on utilise le stockage Supabase (S3-compatible).
_use_supabase_env = os.environ.get("USE_SUPABASE_STORAGE", "false").lower() in ("true", "1", "yes")
_supabase_endpoint = os.environ.get("SUPABASE_S3_ENDPOINT", "").strip()
if VERCEL:
    # Vercel = disque read-only : forcer le backend S3 (Supabase). Sans les clés, l'upload échouera avec une erreur S3 claire.
    USE_SUPABASE_STORAGE = True
    if not _supabase_endpoint:
        logger.warning("Vercel : USE_SUPABASE_STORAGE forcé à True (disque read-only). Définir SUPABASE_S3_* pour que les photos fonctionnent.")
elif _supabase_endpoint or _use_supabase_env:
    USE_SUPABASE_STORAGE = True
else:
    USE_SUPABASE_STORAGE = _use_supabase_env

if USE_SUPABASE_STORAGE:
    # Stockage persistant Supabase (S3-compatible) — Vercel et Render : les images ne sont pas perdues au déploiement.
    # Le chemin est enregistré en base (ex. ads/xxx.webp), le fichier est dans le bucket.
    DEFAULT_FILE_STORAGE = "kiaba.storage_backends.SupabaseS3Storage"
    AWS_ACCESS_KEY_ID = os.environ.get("SUPABASE_S3_ACCESS_KEY_ID") or os.environ.get("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.environ.get("SUPABASE_S3_SECRET_ACCESS_KEY") or os.environ.get("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("SUPABASE_STORAGE_BUCKET", "media")
    AWS_S3_ENDPOINT_URL = os.environ.get("SUPABASE_S3_ENDPOINT")
    AWS_S3_REGION_NAME = os.environ.get("AWS_REGION", "auto")
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=31536000, public"}
    AWS_DEFAULT_ACL = "public-read"
    # Supabase S3 exige souvent le path-style (pas le virtual-hosted)
    AWS_S3_ADDRESSING_STYLE = "path"
    if os.environ.get("SUPABASE_STORAGE_PUBLIC_URL"):
        AWS_S3_CUSTOM_DOMAIN = os.environ.get("SUPABASE_STORAGE_PUBLIC_URL", "").replace("https://", "").replace("http://", "")
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_STORAGE_BUCKET_NAME}/"
    else:
        # Supabase sert les fichiers publics via /object/public/, pas via l'API S3. On dérive l'URL publique depuis l'endpoint S3.
        _endpoint = os.environ.get("SUPABASE_S3_ENDPOINT", "").rstrip("/")
        if _endpoint and "/storage/v1/s3" in _endpoint:
            _public_base = _endpoint.replace("/storage/v1/s3", "/storage/v1/object/public")
            MEDIA_URL = f"{_public_base}/{AWS_STORAGE_BUCKET_NAME}/"
        else:
            MEDIA_URL = os.environ.get("MEDIA_URL", f"{AWS_S3_ENDPOINT_URL or ''}/{AWS_STORAGE_BUCKET_NAME}/")
    MEDIA_ROOT = str(BASE_DIR / "media")
    logger.info("📁 Stockage média : Supabase (S3-compatible) — images persistantes")
elif is_render and not DEBUG:
    # Production sur Render : disque persistant
    MEDIA_ROOT = "/app/media"
    logger.info(f"📁 MEDIA_ROOT configuré pour Render (disque persistant): {MEDIA_ROOT}")
    ads_dir = os.path.join(MEDIA_ROOT, "ads")
    os.makedirs(ads_dir, exist_ok=True)
elif not os.path.isabs(_media_root):
    # Développement local : utiliser le chemin relatif
    MEDIA_ROOT = BASE_DIR / _media_root
    logger.info(f"📁 MEDIA_ROOT configuré pour développement local: {MEDIA_ROOT}")
else:
    # Chemin absolu personnalisé
    MEDIA_ROOT = _media_root
    logger.info(f"📁 MEDIA_ROOT configuré (chemin absolu): {MEDIA_ROOT}")

# S'assurer que le dossier media existe (sauf sur Vercel/serverless, filesystem read-only)
if MEDIA_ROOT and not VERCEL and not USE_SUPABASE_STORAGE:
    os.makedirs(MEDIA_ROOT, exist_ok=True)
if VERCEL and not USE_SUPABASE_STORAGE:
    logger.warning(
        "Vercel : le disque est en lecture seule. Définir SUPABASE_S3_* pour que les photos des annonces s'enregistrent — voir docs/MEDIA_STORAGE.md"
    )
# Diagnostic : quel storage sera utilisé (vérifier les logs Vercel en cas de problème)
_storage_label = "S3/Supabase" if USE_SUPABASE_STORAGE else "FileSystem"
logger.info(
    "📁 Media storage: %s | USE_SUPABASE_STORAGE=%s | VERCEL=%s",
    _storage_label,
    USE_SUPABASE_STORAGE,
    VERCEL,
)
logger.info(f"📁 MEDIA_ROOT final: {MEDIA_ROOT}")

# Django 5.1+ : le stockage par défaut se configure via STORAGES (DEFAULT_FILE_STORAGE est ignoré).
# Sans STORAGES["default"], Django utilise FileSystemStorage → erreur "Read-only file system" sur Vercel.
# Sur Vercel : pas de manifest pour staticfiles (évite "Missing staticfiles manifest entry" si collectstatic diffère).
_staticfiles_backend = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
    if VERCEL
    else "whitenoise.storage.CompressedManifestStaticFilesStorage"
)
if USE_SUPABASE_STORAGE:
    STORAGES = {
        "default": {"BACKEND": "kiaba.storage_backends.SupabaseS3Storage"},
        "staticfiles": {"BACKEND": _staticfiles_backend},
    }
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": _staticfiles_backend},
    }
# Aligner STATICFILES_STORAGE (Django 5.1 utilise STORAGES ; ceci pour collectstatic / rétrocompat)
STATICFILES_STORAGE = _staticfiles_backend

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Sites framework
SITE_ID = 1
# En développement, utiliser localhost:8080, sinon utiliser le domaine de production
if DEBUG:
    SITE_URL = env("SITE_URL", default="http://localhost:8080")
else:
    SITE_URL = env("SITE_URL", default="https://ci-kiaba.com")

# Cache : Redis si REDIS_URL disponible (partagé entre workers), sinon LocMem
_cache_redis_url = os.environ.get("REDIS_URL", "").strip()
if _cache_redis_url:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _cache_redis_url,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

# DRF (prepare throttling for rate limiting contact clicks)
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/minute",
        "user": "300/minute",
    },
}

# CSRF / Security
_base_csrf = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:8001",
    "http://127.0.0.1:8001",
    # Domaine de production (requis pour l'inscription et les formulaires)
    "https://ci-kiaba.com",
    "https://www.ci-kiaba.com",
    "https://ci-kiaba.vercel.app",
]
_dynamic_csrf = []
try:
    from urllib.parse import urlparse as _urlparse

    if SITE_URL:
        _s = _urlparse(SITE_URL)
        if _s.scheme and _s.netloc:
            _dynamic_csrf.append(f"{_s.scheme}://{_s.netloc}")
    if RENDER_EXTERNAL_URL:
        _r = _urlparse(RENDER_EXTERNAL_URL)
        if _r.scheme and _r.netloc:
            _dynamic_csrf.append(f"{_r.scheme}://{_r.netloc}")
    if VERCEL_URL:
        _dynamic_csrf.append(f"https://{VERCEL_URL}")
        _dynamic_csrf.append(f"https://www.{VERCEL_URL}")
except Exception:
    pass
CSRF_TRUSTED_ORIGINS = _base_csrf + _dynamic_csrf
# Page conviviale en français au lieu du 403 brut quand la vérification CSRF échoue
CSRF_FAILURE_VIEW = "core.views.csrf_failure"
# Token CSRF dans la session au lieu d'un cookie séparé : plus fiable quand on arrive
# depuis un lien email (réinitialisation mot de passe, etc.), le cookie CSRF pouvant
# ne pas être posé ou envoyé dans ce contexte.
CSRF_USE_SESSIONS = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "DENY"
# Configuration des cookies CSRF et Session
# En production (HTTPS), activer Secure pour les cookies
# En développement (HTTP), désactiver Secure pour permettre les cookies locaux
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# Renforcer la protection des cookies en toutes circonstances
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
# SameSite pour les cookies CSRF : 'Lax' permet les requêtes GET cross-site mais bloque les POST malveillants
# 'Lax' est un bon compromis entre sécurité et fonctionnalité
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'
# Domaine des cookies : None pour que chaque host (www, non-www, vercel.app) ait son propre cookie.
# .ci-kiaba.com cassait www et vercel.app car le navigateur rejette un cookie Domain=.ci-kiaba.com
# quand la réponse vient de ci-kiaba.vercel.app (pas un sous-domaine).
CSRF_COOKIE_DOMAIN = None
SESSION_COOKIE_DOMAIN = None
# Durée des sessions (14 jours)
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14
SESSION_SAVE_EVERY_REQUEST = True  # Pour que les messages consommés soient bien retirés de la session
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# Politique de referrer : strict-origin-when-cross-origin permet d'envoyer Referer/Origin
# pour les requêtes cross-origin (nécessaire pour CSRF avec www/non-www et proxies)
# "same-origin" était trop stricte et bloquait la vérification CSRF dans certains cas
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
# HSTS : activé en production uniquement (0 en local pour éviter les redirections HTTPS forcées)
# En production : 1 an (31536000s) + inclure sous-domaines + préchargement HSTS
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
# Configuration HTTPS pour les proxies (Render, etc.)
# Render passe le header X-Forwarded-Proto pour indiquer HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# Forcer Django à considérer les requêtes comme sécurisées si le proxy indique HTTPS
USE_TLS = not DEBUG

# CORS (if needed for future API)
CORS_ALLOW_ALL_ORIGINS = DEBUG

"""
Email configuration - SMTP
- En dev : backend console par défaut (ou SMTP si configuré)
- En prod : SMTP configuré via variables d'environnement (LWS, Brevo, SendGrid, etc.)
"""

# Destinataires des emails d'erreurs 500 (Django envoie automatiquement si DEBUG=False)
_admin_email = env("ADMIN_EMAIL", default="")
if _admin_email:
    ADMINS = [("Admin KIABA", _admin_email)]
    MANAGERS = ADMINS

EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend",
)

# Identité d'envoi
DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default="KIABA Rencontres <no-replay@ci-kiaba.com>",
)
SERVER_EMAIL = env(
    "SERVER_EMAIL",
    default="KIABA Rencontres Errors <no-replay@ci-kiaba.com>",
)

# Paramètres SMTP (LWS, Brevo, SendGrid, etc.)
# Configuration via variables d'environnement
EMAIL_HOST = env("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")

# SendGrid HTTP API key (recommandé pour Render, évite les blocages SMTP)
# Si EMAIL_HOST_PASSWORD contient une clé SendGrid (commence par SG.), elle sera utilisée automatiquement
SENDGRID_API_KEY = env("SENDGRID_API_KEY", default="")

# SSL/TLS : généralement 587+TLS ou 465+SSL
# Par défaut, on utilise 587+TLS (plus standard)
EMAIL_USE_SSL = env("EMAIL_USE_SSL", default="False").lower() in ("true", "1", "yes")
EMAIL_USE_TLS = env("EMAIL_USE_TLS", default="True").lower() in ("true", "1", "yes")

EMAIL_TIMEOUT = env.int("EMAIL_TIMEOUT", default=10)  # Timeout pour SMTP
EMAIL_USE_LOCALTIME = True
EMAIL_SUBJECT_PREFIX = "[KIABA] "
EMAIL_USE_8BIT = False
EMAIL_CHARSET = "utf-8"

# En développement local, utiliser console backend par défaut
# Pour tester SMTP en local, configure les variables d'environnement
if DEBUG and not EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
elif EMAIL_HOST:
    # Si EMAIL_HOST est configuré, utiliser SMTP
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Storage (ne pas écraser si Supabase Storage déjà activé plus haut)
if not USE_SUPABASE_STORAGE:
    DEFAULT_FILE_STORAGE = env("DEFAULT_FILE_STORAGE")

# Google Analytics
GA_MEASUREMENT_ID = env("GA_MEASUREMENT_ID", default=None)

# Google AdSense
ADSENSE_PUBLISHER_ID = env(
    "ADSENSE_PUBLISHER_ID", default="ca-pub-3273662002214639"
)  # Format: ca-pub-XXXXXXXXXX
ADSENSE_ENABLED = env("ADSENSE_ENABLED", default="True").lower() in ("true", "1", "yes")

# Celery (broker/backend via Redis ou base de données)
REDIS_URL = env("REDIS_URL", default=None)
if REDIS_URL and REDIS_URL.strip():
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL
    CELERY_TASK_ALWAYS_EAGER = False  # Utiliser Celery avec Redis
else:
    # Fallback memory (évite le warning Kombu "No hostname was supplied")
    CELERY_BROKER_URL = "memory://localhost/"
    CELERY_RESULT_BACKEND = "cache+memory://"
    # En production sans Redis, exécuter les tâches Celery en mode synchrone
    CELERY_TASK_ALWAYS_EAGER = True  # Mode synchrone si pas de Redis

CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_BEAT_SCHEDULE = {
    "expire-ads-daily": {
        "task": "ads.tasks.expire_ads",
        "schedule": 60 * 60 * 24,  # quotidien
    }
}

# Traitement des images (filigrane + miniature) en arrière-plan pour réponses rapides (post / edit annonce).
# N'activer qu'avec un broker Redis : sans Redis, Celery tourne en eager et bloquerait quand même la requête.
USE_ASYNC_IMAGE_PROCESSING = (
    bool(REDIS_URL and REDIS_URL.strip())
    and os.environ.get("USE_ASYNC_IMAGE_PROCESSING", "true").lower() in ("true", "1", "yes")
)

# Sitemaps
SITEMAP_PROTOCOL = "https"

# Authentication backends (allauth + Django)
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

# allauth basic settings (we'll restrict provider signups later via adapter/forms)
ACCOUNT_AUTHENTICATION_METHOD = "username_email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # Obligatoire pour valider les comptes
LOGIN_REDIRECT_URL = "/dashboard"
LOGIN_URL = "/auth/login/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
ACCOUNT_EMAIL_CONFIRMATION_AUTO_LOGIN = True
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "/auth/login/"
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "/dashboard/"

# Rate limiting allauth pour limiter les tentatives de bruteforce & abus
# (utilise le cache Django ; ici LocMem en production sans Redis)
ACCOUNT_RATE_LIMITS = {
    "login_failed": "3/5m",  # max 3 échecs de login / 5 minutes par IP+user (anti brute-force)
    "signup": "3/h",  # max 3 inscriptions / heure
    "reset_password": "3/h",  # max 3 demandes de reset / heure
}

# Désactiver la page de confirmation de déconnexion
ACCOUNT_LOGOUT_ON_GET = True

# Utiliser l'adaptateur personnalisé
ACCOUNT_ADAPTER = "accounts.adapters.NoRateLimitAccountAdapter"

# Utiliser les formulaires personnalisés
ACCOUNT_FORMS = {
    "login": "accounts.forms.CustomLoginForm",
    "signup": "accounts.forms.CustomSignupForm",
}

# Connexion / inscription avec Google (OAuth 2.0)
# Créer des identifiants : https://console.cloud.google.com/apis/credentials → Créer des identifiants OAuth 2.0
# URI de redirection autorisés : https://ci-kiaba.com/auth/google/login/callback/ (et http://localhost:8000/auth/google/login/callback/ en dev)
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "APPS": [
            {
                "client_id": os.environ.get("GOOGLE_OAUTH_CLIENT_ID", ""),
                "secret": os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", ""),
                "key": "",
            }
        ],
    }
}
# Comptes créés via Google : pas de vérification email (déjà vérifié par Google)
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_AUTO_SIGNUP = True
# Redirection directe vers Google sans page « Vous êtes sur le point de vous connecter... »
SOCIALACCOUNT_LOGIN_ON_GET = True

# Custom user model
AUTH_USER_MODEL = "accounts.CustomUser"

# CinetPay configuration
CINETPAY_SITE_ID = env("CINETPAY_SITE_ID", default="")
CINETPAY_API_KEY = env("CINETPAY_API_KEY", default="")
CINETPAY_SITE_KEY = env("CINETPAY_SITE_KEY", default="")
CINETPAY_MODE = env("CINETPAY_MODE", default="PRODUCTION")  # PRODUCTION ou TEST
CINETPAY_NOTIFY_URL = env(
    "CINETPAY_NOTIFY_URL", default="https://ci-kiaba.com/accounts/payment/cinetpay/notify/"
)
CINETPAY_RETURN_URL = env(
    "CINETPAY_RETURN_URL", default="https://ci-kiaba.com/accounts/payment/cinetpay/return/"
)

# Superuser initial (créé par create_initial_superuser) : mot de passe via env uniquement
INITIAL_SUPERUSER_PASSWORD = os.environ.get("INITIAL_SUPERUSER_PASSWORD", "").strip() or None
