# Generated by Django 5.1.2 on 2025-12-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_ad_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('maisons_appartements', 'Maisons et Appartements'), ('villas_residences', 'Villas et Résidences'), ('terrains', 'Terrains'), ('locations', 'Locations')], max_length=20),
        ),
    ]
