# Generated by Django 5.1.2 on 2025-12-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_add_additional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='additional_data',
            field=models.JSONField(default=dict, help_text='Données supplémentaires selon la catégorie (prix, surface, etc.)'),
        ),
    ]
