# Generated by Django 5.2.13 on 2026-04-12 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_indexes_phone_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_e164',
            field=models.CharField(blank=True, db_index=True, help_text='Phone number in E.164 format, e.g., +2250700000000', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{1,14}$', message='Entrez un numéro au format E.164 (ex: +225XXXXXXXXXX)')]),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone2_e164',
            field=models.CharField(blank=True, db_index=True, help_text='Second phone number for ads (optional). Shown with primary on ad contact.', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{1,14}$', message='Entrez un numéro au format E.164 (ex: +225XXXXXXXXXX)')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp_e164',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{1,14}$', message='Entrez un numéro au format E.164 (ex: +225XXXXXXXXXX)')]),
        ),
    ]
